### ISSUE TITLE
Scss does not compile

### ISSUE THREAD

**Issue by ghost** [jeromev/baselinegrid.scss#1]
Hi Jerome,

Thanks for building this. I gave it a shot on a Jekyll site I use for testing. Unfortunately, when I try to build it throws up errors on the lines with !global. Not sure what the issue might be. Do I need to compile this with something else?

Thanks,

Jeff

**Comment by denisbrodbeck** [comment]
Hi Jeff,

you've got this issue, because `!global` is only available since [sass 3.3](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#330_7_march_2014).

When upgrading to the latest sass is not possible, you could get away by editing `grid.scss` and replacing all instances of `!global` with `!default`.
